"use client";

import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Timestamp } from "@/components/timestamp";
import type { AiSummary } from "@/lib/types";

const CONFIDENCE_STYLES: Record<string, string> = {
  high: "bg-emerald-100 text-emerald-800 border-emerald-200",
  medium: "bg-amber-100 text-amber-800 border-amber-200",
  low: "bg-slate-100 text-slate-700 border-slate-200",
};

/**
 * doc 05: states none / queued / generating / failed / ready / edited. Generation itself is
 * phase 8 — this card renders whatever the incident row says, so it lights up on its own once
 * the processor stops stubbing.
 */
export function AiSummaryCard({ status, summary }: { status: string; summary: AiSummary | null }) {
  return (
    <section className="rounded-lg border p-4">
      <div className="mb-3 flex items-center justify-between gap-2">
        <h2 className="text-sm font-semibold">AI incident summary</h2>
        {summary?.confidence && (
          <Badge variant="outline" className={CONFIDENCE_STYLES[summary.confidence] ?? ""}>
            {summary.confidence} confidence
          </Badge>
        )}
      </div>

      {status === "none" && (
        <p className="text-muted-foreground text-sm">
          No summary yet. One is drafted automatically when the health engine opens an incident.
        </p>
      )}

      {status === "queued" && (
        <p className="text-muted-foreground text-sm">Queued — waiting for a summarizer worker.</p>
      )}

      {status === "generating" && (
        <div className="space-y-2">
          <Skeleton className="h-4 w-3/4" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-2/3" />
        </div>
      )}

      {status === "failed" && (
        <p className="text-sm text-red-600">
          Summary generation failed. Ops can regenerate it from this card.
        </p>
      )}

      {(status === "ready" || status === "edited") && summary && (
        <div className="space-y-3 text-sm">
          <p>{summary.summary}</p>
          <div>
            <p className="text-muted-foreground text-xs font-medium uppercase">Probable cause</p>
            <p>{summary.probableCause}</p>
          </div>
          <div>
            <p className="text-muted-foreground text-xs font-medium uppercase">Impact</p>
            <p>{summary.impact}</p>
          </div>
          {summary.suggestedSteps?.length > 0 && (
            <div>
              <p className="text-muted-foreground text-xs font-medium uppercase">Suggested steps</p>
              <ul className="mt-1 space-y-1">
                {summary.suggestedSteps.map((step, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="text-muted-foreground">{i + 1}.</span>
                    <span>{step}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          <p className="text-muted-foreground border-t pt-2 text-xs">
            Generated by {summary.model ?? "unknown model"} · prompt {summary.promptVersion ?? "n/a"}
            {summary.generatedAt && (
              <>
                {" · "}
                <Timestamp date={summary.generatedAt} />
              </>
            )}
            {status === "edited" && summary.editedBy && <> · edited by {summary.editedBy}</>}
          </p>
        </div>
      )}
    </section>
  );
}
